spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  mail:
    host: smtp.163.com
    port: 25
    username: cqkctandroidt
    password: cqkct123
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.shiro.pojo
